version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  gierka:
    image: 992382713357.dkr.ecr.eu-north-1.amazonaws.com/gierka:latest
    ports:
      - 4000:4000

  gierka-mongo:
    image: 992382713357.dkr.ecr.eu-north-1.amazonaws.com/gierka-mongo:latest
    ports:
      - 4001:4001

volumes:
  mongodb-data:
    driver: local
