version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

  gierka:
    image: 891377250379.dkr.ecr.us-east-1.amazonaws.com/kontener_backend:latest
    ports:
      - 4000:4000

  gierka-mongo:
    image: 891377250379.dkr.ecr.us-east-1.amazonaws.com/kontener_mongo:latest
    ports:
      - 4001:4001

  gierka-api:
    image: 891377250379.dkr.ecr.us-east-1.amazonaws.com/kontener_api:latest
    ports:
      - 4002:4002

volumes:
  mongodb-data:
    driver: local
